let foo; try {} catch (foo) {} let foo;
