# `harness.test.ts`

**DO NOT MODIFY**. This file has been autogenerated. Run `rome test internal/compiler/lint/rules/harness.test.ts --update-snapshots` to update.

## `js/noUnsafeFinally`

### `0`

```

 lint/js/noUnsafeFinally/reject/1/file.ts:7:2 lint/js/noUnsafeFinally ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Using JSReturnStatement inside a finally clause is unsafe.

    5 │     throw err;
    6 │   } finally {
  > 7 │     return 1;
      │     ^^^^^^^^^
    8 │   }
    9 │ }

  ℹ Do not use control flow statements inside finally clauses.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✖ Found 1 problem

```

### `0: formatted`

```ts
function greet1() {
	try {
		throw new Error("Try");
	} catch (err) {
		throw err;
	} finally {
		return 1;
	}
}

```

### `1`

```

 lint/js/noUnsafeFinally/reject/2/file.ts:7:2 parse/js ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ No loop label found

    5 │     throw err;
    6 │   } finally {
  > 7 │     break;
      │     ^
    8 │   }
    9 │ }

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✖ Found 1 problem

```

### `1: formatted`

```javascript
undefined
```

### `2`

```

 lint/js/noUnsafeFinally/reject/3/file.ts:7:2 parse/js ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ No loop label found

    5 │     throw err;
    6 │   } finally {
  > 7 │     continue;
      │     ^
    8 │   }
    9 │ }

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✖ Found 1 problem

```

### `2: formatted`

```javascript
undefined
```

### `3`

```

 lint/js/noUnsafeFinally/reject/4/file.ts:7:2 lint/js/noUnsafeFinally ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Using JSThrowStatement inside a finally clause is unsafe.

    5 │     throw err;
    6 │   } finally {
  > 7 │     throw new Error('Finally');
      │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    8 │   }
    9 │ }

  ℹ Do not use control flow statements inside finally clauses.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✖ Found 1 problem

```

### `3: formatted`

```ts
function greet4() {
	try {
		throw new Error("Try");
	} catch (err) {
		throw err;
	} finally {
		throw new Error("Finally");
	}
}

```
